Concatenate sub-block names for blocks that contain multiple sub-blocks
dnanexus/dxCompiler pull request #120
Opened 2021-05-18 17:28 UTC by jdidion

2021-05-19 14:59 UTC, r-i-v-a commented
@jdidion  Could you also add a changelog note?

2021-05-19 14:59 UTC, r-i-v-a requested changes
Just add changelog note

2021-05-20 15:55 UTC, jdidion commented
@r-i-v-a note added

2021-05-21 14:11 UTC, r-i-v-a approved these changes

2021-05-21 15:38 UTC, merged