put reserved parameters in a group
dnanexus/dxCompiler pull request #214
Opened 2021-11-08 17:26 UTC by jdidion

2021-11-09 18:49 UTC, commandlinegirl commented on RELEASE_NOTES.md
> +* Reserved parameters are now placed in the "Reserved" parameter group (only affects the display of the app/workflow in the UI)
Should we name the group something that is very clear to the user that it's something system-like, set by `dxCompiler`? E.g. `Reserved for dxCompiler (do not change)` or just `Reserved for dxCompiler`.

2021-11-09 18:52 UTC, commandlinegirl commented on compiler/src/main/scala/dx/compiler/ExecutableCompiler.scala
> +  // these parameters are used for applets and workflows that are generated with useManifests=true.
Would it be possible to add a short comment on why the overrides are needed?

2021-11-10 11:19 UTC, r-i-v-a requested changes
What Ola said about adding comment.

2021-11-10 14:33 UTC, r-i-v-a submitted a review, later dismissed

2021-11-10 17:35 UTC, merged