APPS-928 Add instanceTypeSelection to task & workflow annotations.
dnanexus/dxCompiler pull request #236
Opened 2021-11-18 18:22 UTC by r-i-v-a

2021-11-22 16:05 UTC, r-i-v-a commented
PR https://github.com/dnanexus/dxCompiler/pull/236

Once this is merged, I will be able to start a release of dxCompiler with initial support for creating global WDL workflows, which can be used as the comparison version in the APPS-624 dx-toolkit PR. @jdidion  @commandlinegirl

2021-11-22 16:30 UTC, r-i-v-a commented
Waiting for current integration tests run to finish, but previous runs have succeeded
-- https://github.com/dnanexus/dxCompiler/actions/runs/1490337969
-- https://github.com/dnanexus/dxCompiler/actions/runs/1490367072

2021-11-22 17:43 UTC, jdidion requested changes

2021-11-22 17:43 UTC, jdidion commented on compiler/src/main/scala/dx/compiler/ApplicationCompiler.scala
> +        s"${listMd(
`listMd` returns a string - why put it inside an interpolation?

2021-11-22 17:43 UTC, jdidion commented on compiler/src/main/scala/dx/compiler/WorkflowCompiler.scala
> +                "Available instance types determined during WDL compilation will be " +
same here

2021-11-23 17:04 UTC, jdidion approved these changes

2021-11-23 17:37 UTC, merged