APPS-991-document-reuse
dnanexus/dxCompiler pull request #272
Opened 2022-01-05 09:56 UTC by mhrvol

2022-01-06 22:24 UTC, commandlinegirl commented on README.md
>      * For example, if `A.wdl` imports `B.wdl` and `A.wdl` defines `workflow foo`, then `B.wdl` could not have a workflow or task named `foo`
```suggestion
    * For example, if `A.wdl` imports `B.wdl` and `A.wdl` defines workflow `foo`, then `B.wdl` could not have a workflow or task named `foo`
```
```suggestion
    * For example, if `A.wdl` imports `B.wdl` and `A.wdl` defines `workflow foo`, then `B.wdl` could not have a workflow or task named `foo`
```

2022-01-06 22:24 UTC, commandlinegirl commented on README.md
> +  * Compilation of subworkflows(subtasks) used from different workflow files will create new workflows(applets), thus reuse is not available between built workflows.
Let's discuss it in person how we can make it clearer.

2022-02-07 17:44 UTC, emiloslavsky requested changes

2022-02-07 17:44 UTC, emiloslavsky commented on README.md
> +  * Compilation of subworkflows(subtasks) used from different workflow files will create new workflows(applets), thus reuse is not available between built workflows.
Need to document the fact that DNAnexus subworkflows rely on the top-level workflow context and explicitly mention the dependencies of the DNAnexus subworkflow on the top-level workflow

2022-02-22 16:49 UTC, commandlinegirl approved these changes, later dismissed
LGTM, with a minor change suggestion

2022-02-22 16:49 UTC, commandlinegirl commented on README.md
> +    * For example, if `A.wdl` imports `B.wdl` and `A.wdl` defines workflow `foo`, then `B.wdl` could not have a workflow or task named `foo`
could not -> cannot

2022-02-23 18:17 UTC, commandlinegirl approved these changes

2022-02-23 18:18 UTC, merged