APPS-1006 Update include task error trace
dnanexus/dxCompiler pull request #300
Opened 2022-02-10 23:23 UTC by Gvaihir

This PR addresses error propagation from a task to the main process

2022-02-22 22:54 UTC, commandlinegirl requested changes
A minor thing: in `test/subworkflows/` we store tests that are about nested workflows, i.e. workflows calling other workflows in their stages. Nota bene we also have `test/nested/` so we should merge these two at some point. 

I suggest moving your tests, for example to https://github.com/dnanexus/dxCompiler/tree/develop/test/single_tasks

If you haven't done so locally, ie. starting integration tests from your local machine, you can run integration tests from GitHub by adding the `integration` label. Then each new commit will run them, so if you plan more commits you can remove the label and add again at the end. We don't run these tests automatically at commits so as not to generate too much cost.

Thanks!

2022-02-22 22:54 UTC, commandlinegirl commented on scripts/run_tests.py
> +expected_failure_msg = {
That's a useful category, thanks!

2022-02-22 23:03 UTC, Gvaihir commented
> A minor thing: in `test/subworkflows/` we store tests that are about nested workflows, i.e. workflows calling other workflows in their stages. Nota bene we also have `test/nested/` so we should merge these two at some point.
> 
> I suggest moving your tests, for example to https://github.com/dnanexus/dxCompiler/tree/develop/test/single_tasks

Thanks! Fixed in [7d61a26](https://github.com/dnanexus/dxCompiler/pull/300/commits/7d61a26d0d4059625db3fa15803d1138f48ba279)
 
> If you haven't done so locally, ie. starting integration tests from your local machine, you can run integration tests from GitHub by adding the `integration` label. Then each new commit will run them, so if you plan more commits you can remove the label and add again at the end. We don't run these tests automatically at commits so as not to generate too much cost.

I have triggered integration tests covering 2 new tests only, not the full suite. Will start full integration testing from GHA shortly

2022-02-23 00:27 UTC, commandlinegirl approved these changes
LGTM, thank you!

2022-02-23 02:01 UTC, merged