Add release action
dnanexus/dxCompiler pull request #44
Opened 2021-01-12 18:10 UTC by jdidion

Adds a GHA for releases. Right now the only difference is that it runs the large integration test suite, as opposed to "integration" which runs the medium test suite. In the future, this action could be improved to automatically create GitHub releases for artifacts.

2021-01-12 22:41 UTC, commandlinegirl requested changes
Thanks for this starter task! We'll need to take into account issues mentioned in  https://jira.internal.dnanexus.com/browse/APPS-324 when following up on this.

2021-01-12 22:41 UTC, commandlinegirl commented on .github/workflows/release.yml
> +    if: contains(github.event.pull_request.labels.*.name, 'integration')
We don't want to run the release and large tests with every commit to a PR labelled 'integration' . So how about for the release a label 'release' needs to be used?

Perhaps there is even a better trigger available - one where we don't need to create a PR to run a release.

2021-01-12 22:41 UTC, commandlinegirl commented on .github/workflows/integration.yml
> +    name: dxCompiler Release Tests (Staging)
This should rather be dxCompiler Integration Tests (Staging) and github/workflows/release.yml  -> dxCompiler Release(Staging)

2021-01-15 15:21 UTC, jdidion commented
The test names have changed. After "dxCompiler Unit Tests" and " dxCompiler Integration Tests" pass, we'll need to force the merge and then update branch protection rules to disable "Scala Unit Tests" and "WDL Integration Tests".

2021-01-16 14:16 UTC, commandlinegirl commented
> The test names have changed. After "dxCompiler Unit Tests" and " dxCompiler Integration Tests" pass, we'll need to force the merge and then update branch protection rules to disable "Scala Unit Tests" and "WDL Integration Tests".

After updating the `main` branch protection rules already, the PR only requires the newly named pipelines to pass so I don't think we need to force merge:

![image](https://user-images.githubusercontent.com/2283292/104814159-30dd1800-57c2-11eb-930a-4cc7f20c13d9.png)

2021-01-16 14:18 UTC, commandlinegirl commented
I marked the old ones back so other current PRs can pass.

2021-02-17 14:28 UTC, closed without merging