APPS-1857 tar_io_doc
dnanexus/dxCompiler pull request #447
Opened 2023-06-06 06:44 UTC by Gvaihir

(feat) Tips.md - tar advice

2023-06-13 08:29 UTC, commandlinegirl requested changes
A couple of minor requests, this is useful, thank you!

2023-06-13 08:29 UTC, commandlinegirl commented on doc/Tips.md
> +When passing a large number of files from stage to stage, we recommend doing that in the form of a `tar.gz` archive to
Can you provide a ballpark amount of files we mean, e.g. 

```
... a large number of files, i.e. larger than 1000, from ...
```

?

2023-06-13 08:29 UTC, commandlinegirl commented on doc/Tips.md
> +**Scenario 1.** Stage A creates `N` files to be used only by Stage B, and there is no need for a separate archiving task.
Here you refer to `Stage A` and `Stage B` but in the code there are tasks, so I'd suggest to change it to Task A/B.

2023-06-13 08:29 UTC, commandlinegirl commented on doc/Tips.md
> +**Scenario 2.** Stage A creates `N` files to be used by Stage B, C, ... m, and it makes sense to refactor the archiving
```suggestion
**Scenario 2.** Stage A creates `N` files to be used by multiple tasks B, C, ...M, here represented by `task_b_c_through_m`, by and it makes sense to refactor the archiving 
```

2023-06-13 18:30 UTC, Gvaihir commented on doc/Tips.md
> +When passing a large number of files from stage to stage, we recommend doing that in the form of a `tar.gz` archive to
Hm, that was updated in [306022e](https://github.com/dnanexus/dxCompiler/pull/447/commits/306022eede1280c6c5b79076a3c7d631cb69fa6c)

2023-06-13 18:31 UTC, Gvaihir commented on doc/Tips.md
> +**Scenario 1.** Stage A creates `N` files to be used only by Stage B, and there is no need for a separate archiving task.
This was too resoled in [306022e](https://github.com/dnanexus/dxCompiler/pull/447/commits/306022eede1280c6c5b79076a3c7d631cb69fa6c)

2023-06-14 10:25 UTC, commandlinegirl approved these changes
LGTM, thank you!

2023-06-14 10:26 UTC, commandlinegirl commented on doc/Tips.md
> +When passing a large number of files from stage to stage, we recommend doing that in the form of a `tar.gz` archive to
True, it was a stale come from when I started the review. Resolving.

2023-06-15 21:38 UTC, merged