APPS-544 - don't create default value for file-type outputs
dnanexus/dxCompiler pull request #99
Opened 2021-04-20 20:33 UTC by jdidion

If an output parameter has expression that is a File, Directory or collection thereof, the paths will be local to the worker so we cannot use them as the default value (since file inputs need to be given as links to dx files).

This PR also activates some additional integration tests and removes unused tests.

2021-04-20 22:38 UTC, commandlinegirl submitted a review, later dismissed
LGTM

2021-04-22 20:05 UTC, commandlinegirl requested changes
Minor

2021-04-22 20:05 UTC, commandlinegirl commented on scripts/build_all_releases.sh
> +    echo "  --branch <string>: branch to build from (default=main)"
Thanks for this!

2021-04-22 20:41 UTC, jdidion commented on build.sbt
> +resolvers += githubResolver
it is used to resolve snapshot packages stored in GitHub packages

2021-04-22 20:44 UTC, commandlinegirl approved these changes

2021-04-22 20:45 UTC, merged